version: '2'
services:
  project-admin:
    image: project/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  project-api:
    image: project/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev